# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3cda946f356986690ddd171468be2e979442c507140e1fef96d356e4813fbc46010a1afd2b0454ce6a72c90cb4407818843df1581181d41d47a2f8f985e70f74

test:
  secret_key_base: 092f3da8f80d33e3f1f1249349fcad7ba282df0c3a4fe5e31116b8434f9b4c2418292fbea6eafdaff102c0d2b5135c9b0ef42991124055a922ab46f92bd580b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
